// <auto-generated />
namespace MoneyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddTableNewMoney : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTableNewMoney));
        
        string IMigrationMetadata.Id
        {
            get { return "202003071547505_AddTableNewMoney"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
